version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /workflow/cli
    schedule:
      interval: weekly
    groups:
      compatible-dependencies:
        patterns: ['*']
        update-types: [minor, patch]
